### ISSUE TITLE
Export todo.txt

### ISSUE THREAD

**Issue by Krostyna** [CoToDo/CoToDo#23]
- [x] opravit priority, pokud je ukol splneny priorita je vypsana jako posledni "pri:A" ne na zacatku
- [x] pridat due: do kdy se ma splnit ukol
- [x] format by mel byt asi bez hodin a minut? DateTime zmenit na date
- [x] probrat skipovani mezer
